# Cop supports --auto-correct.
# Configuration parameters: AlignWith, SupportedStyles.
# SupportedStyles: either, start_of_block, start_of_line
Lint/BlockAlignment:
  Exclude:
    - 'app/models/item.rb'

# Cop supports --auto-correct.
# Configuration parameters: AlignWith, SupportedStyles, AutoCorrect.
# SupportedStyles: start_of_line, def
Lint/DefEndAlignment:
  Enabled: false

# Cop supports --auto-correct.
Lint/DeprecatedClassMethods:
  Exclude:
    - 'config/boot.rb'
    - 'config/unicorn/production.rb'
    - 'config/unicorn/staging.rb'
    - 'config/unicorn/uat.rb'
    - 'lib/tasks/archive.rake'

# Cop supports --auto-correct.
# Configuration parameters: AlignWith, SupportedStyles, AutoCorrect.
# SupportedStyles: keyword, variable, start_of_line
Lint/EndAlignment:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'config/unicorn/production.rb'
    - 'config/unicorn/staging.rb'
    - 'config/unicorn/uat.rb'

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'app/models/user.rb'

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'app/controllers/collections_controller.rb'
    - 'app/controllers/items_controller.rb'

# Cop supports --auto-correct.
Lint/StringConversionInInterpolation:
  Exclude:
    - 'app/controllers/items_controller.rb'

# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks.
Lint/UnusedBlockArgument:
  Exclude:
    - 'app/admin/latlon_boundary.rb'
    - 'app/admin/users.rb'
    - 'app/controllers/collections_controller.rb'
    - 'app/controllers/items_controller.rb'
    - 'app/controllers/oai_controller.rb'
    - 'config/unicorn/production.rb'
    - 'config/unicorn/staging.rb'
    - 'config/unicorn/uat.rb'
    - 'lib/tasks/archive.rake'
    - 'spec/controllers/essences_controller_spec.rb'

# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/tasks/archive.rake'

Lint/UselessAssignment:
  Exclude:
    - 'config/unicorn/production.rb'
    - 'config/unicorn/staging.rb'
    - 'config/unicorn/uat.rb'
    - 'lib/tasks/archive.rake'
    - 'spec/support/select2.rb'
